# #####################################################################
# Automatically generated by qmake (1.02a) Fri May 31 15:29:14 2002
# #####################################################################
TEMPLATE = subdirs
SUBDIRS = ar2gems
# Directories

