# #####################################################################
# Automatically generated by qmake (1.02a) Fri May 31 15:29:14 2002
# #####################################################################
TEMPLATE = subdirs
CONFIG += debug
# Directories
SUBDIRS = GsTLAppli
SOURCES = GsTLAppli/.metadata/.plugins/org.eclipse.cdt.make.core/specs.c \
    GsTLAppli/.metadata/.plugins/org.eclipse.cdt.make.core/specs.cpp
