##############################################################
# Automatically generated by qmake Sun May 19 20:55:49 2002
##############################################################

TEMPLATE = subdirs
SUBDIRS = utils appli math grid geostat extra/qtplugins filters actions charts extra/qwt  gui extra/gui main
CONFIG += ordered


